# 01 · Recolección, limpieza y EDA

## Configuración inicial

| Dato | Valor |
|---|---|
| **Fecha de descarga** | 2026-10-26, 16:23 (hora de Lima) |
| **Medio elegido** | **B: El Comercio** |
| **URL base** | https://elcomercio.pe/ |

**URLs base por sección** (de cada una se toman las 90 noticias más recientes):

| Sección | URL de la sección | Fuente del listado (sitemap de noticias) | `etiqueta` |
|---|---|---|---|
| Economía | https://elcomercio.pe/economia/ | https://elcomercio.pe/sitemap/news/economia/?outputType=xml | `economia` |
| Política | https://elcomercio.pe/politica/ | https://elcomercio.pe/sitemap/news/politica/?outputType=xml | `politica` |
| DT (deporte) | https://elcomercio.pe/deporte-total/ | https://elcomercio.pe/sitemap/news/deporte-total/?outputType=xml | `deportes` |
| Ciencia y Tecnología | https://elcomercio.pe/tecnologia/ | https://elcomercio.pe/sitemap/news/tecnologia/?outputType=xml | `ciencia_tecnologia` |

## Objetivo

Construir `datos/noticias.csv` con las **360 noticias más recientes** (90 por sección). Si una sección no tiene suficientes noticias, el faltante se compensa con las secciones que tengan más publicadas.

## 0. Configuración (ejecutar primero)

Usa el kernel **Python (tarea_1)** (o `tarea_1/.venv/bin/python`). Ejecuta esta celda antes que cualquier otra: aquí se importan `pandas`, `requests`, `BeautifulSoup`, etc. Si reinicias el kernel, vuelve a ejecutarla.

In [1]:
import time
from datetime import datetime
from pathlib import Path

import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm.auto import tqdm
import plotly.express as px

DATOS = Path("datos")
RAW = DATOS / "raw"  # respaldo crudo de todo lo descargado
(RAW / "sitemaps").mkdir(parents=True, exist_ok=True)
(RAW / "html").mkdir(parents=True, exist_ok=True)

BASE = "https://elcomercio.pe"
MEDIO = "El Comercio"
TOTAL = 360
PAUSA = 0.5  # segundos de espera entre peticiones
SECCIONES = {  # sección en la web -> etiqueta oficial
    "economia": "economia",
    "politica": "politica",
    "deporte-total": "deportes",
    "tecnologia": "ciencia_tecnologia",
}

sesion = requests.Session()
sesion.headers["User-Agent"] = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/130 Safari/537.36"
)

/Users/susanmontalvo/Documents/GitHub/Diplomado-Su-2026/tarea_1/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Scraping

Todas las peticiones se hacen con `requests`, con una pausa de `PAUSA` segundos entre cada una, y cada respuesta se guarda tal cual en `datos/raw/` (respaldo crudo):

| Archivo | Contenido |
|---|---|
| `datos/raw/sitemaps/<seccion>.xml` | Listado de noticias de cada sección |
| `datos/raw/html/<seccion>_<nnn>.html` | Página HTML de cada noticia |
| `datos/raw/noticias_crudo.csv` | Datos extraídos, antes de la limpieza |

### 1.1 Listado de noticias por sección

El Comercio publica un sitemap de Google News por sección (`/sitemap/news/<seccion>/`) con las 100 notas más recientes: URL, titular y fecha de publicación.

In [2]:
def descargar(url: str, destino: Path, intentos: int = 3) -> bytes:
    """GET con reintentos: guarda la respuesta cruda en `destino` y luego hace una pausa."""
    for intento in range(intentos):
        try:
            resp = sesion.get(url, timeout=20)
            resp.raise_for_status()
            break
        except requests.RequestException:
            if intento == intentos - 1:
                raise
            time.sleep(2 * (intento + 1))
    destino.write_bytes(resp.content)
    time.sleep(PAUSA)  # ser respetuosos con el servidor
    return resp.content


def listar_seccion(seccion: str) -> pd.DataFrame:
    url = f"{BASE}/sitemap/news/{seccion}/?outputType=xml"
    sitemap = BeautifulSoup(descargar(url, RAW / "sitemaps" / f"{seccion}.xml"), "xml")
    filas = []
    for nodo in sitemap.find_all("url"):
        news = nodo.find("news")
        filas.append({
            "titular": news.find("title").get_text(strip=True),
            "url": nodo.find("loc").get_text(strip=True),
            "publicado": news.find("publication_date").get_text(strip=True),
            "seccion_web": seccion,
        })
    return pd.DataFrame(filas)


print("Fecha de descarga:", datetime.now().strftime("%Y-%m-%d %H:%M"))
listado = (
    pd.concat([listar_seccion(s) for s in SECCIONES], ignore_index=True)
    .sort_values("publicado", ascending=False)
    .drop_duplicates(subset="url")
)
listado["seccion_web"].value_counts()

Fecha de descarga: 2026-10-26 16:23

seccion_web
deporte-total    100
economia         100
politica         100
tecnologia        99
Name: count, dtype: int64

### 1.2 Cuota por sección

90 por sección (`TOTAL / 4`). Si alguna tiene menos, el faltante se asigna una a una a la sección con más noticias sobrantes.

In [3]:
def repartir_cuotas(disponibles: dict[str, int], total: int) -> dict[str, int]:
    cuotas = {s: min(n, total // len(disponibles)) for s, n in disponibles.items()}
    faltan = total - sum(cuotas.values())
    while faltan > 0:
        sobrantes = {s: disponibles[s] - cuotas[s] for s in cuotas if disponibles[s] > cuotas[s]}
        if not sobrantes:
            break
        cuotas[max(sobrantes, key=sobrantes.get)] += 1
        faltan -= 1
    return cuotas


cuotas = repartir_cuotas(listado["seccion_web"].value_counts().to_dict(), TOTAL)
seleccion = pd.concat(
    [listado[listado["seccion_web"] == s].head(n) for s, n in cuotas.items()], ignore_index=True
)
cuotas, len(seleccion)

({'deporte-total': 90, 'economia': 90, 'politica': 90, 'tecnologia': 90}, 360)

### 1.3 Bajada y sección original de cada nota

Se descarga el HTML de cada noticia (con su respaldo en `datos/raw/html/`): la bajada es la `meta description` y la sección original es el `section-id` de la página (p. ej. `/tecnologia/ciencias` → `tecnologia-ciencias`).

In [4]:
def meta(soup: BeautifulSoup, **attrs) -> str | None:
    tag = soup.find("meta", attrs=attrs)
    return tag["content"].strip() if tag and tag.get("content") else None


def detalle_noticia(url: str, archivo: Path) -> dict:
    try:
        soup = BeautifulSoup(descargar(url, archivo), "lxml")
    except requests.RequestException:
        return {"bajada": None, "seccion_original": None}
    ruta = meta(soup, name="section-id") or "/".join(url.removeprefix(BASE).split("/")[:-2])
    return {
        "bajada": meta(soup, name="description") or meta(soup, property="og:description"),
        "seccion_original": ruta.strip("/").replace("/", "-"),
    }


numero = seleccion.groupby("seccion_web").cumcount() + 1
seleccion["archivo_raw"] = seleccion["seccion_web"] + "_" + numero.map("{:03d}".format) + ".html"

detalles = [
    detalle_noticia(url, RAW / "html" / archivo)
    for url, archivo in tqdm(zip(seleccion["url"], seleccion["archivo_raw"]), total=len(seleccion), desc="Noticias")
]

df = pd.concat([seleccion, pd.DataFrame(detalles)], axis=1)
df.to_csv(RAW / "noticias_crudo.csv", index=False)  # respaldo antes de limpiar
df.shape

Noticias:   0%|          | 0/360 [00:00<?, ?it/s]

Noticias:   0%|          | 1/360 [00:00<03:41,  1.62it/s]

Noticias:   1%|          | 2/360 [00:01<03:57,  1.50it/s]

Noticias:   1%|          | 3/360 [00:02<04:00,  1.48it/s]

Noticias:   1%|          | 4/360 [00:02<03:49,  1.55it/s]

Noticias:   1%|▏         | 5/360 [00:03<03:44,  1.58it/s]

Noticias:   2%|▏         | 6/360 [00:04<04:18,  1.37it/s]

Noticias:   2%|▏         | 7/360 [00:05<04:51,  1.21it/s]

Noticias:   2%|▏         | 8/360 [00:05<04:36,  1.27it/s]

Noticias:   2%|▎         | 9/360 [00:06<04:58,  1.18it/s]

Noticias:   3%|▎         | 10/360 [00:07<04:29,  1.30it/s]

Noticias:   3%|▎         | 11/360 [00:08<05:03,  1.15it/s]

Noticias:   3%|▎         | 12/360 [00:09<04:57,  1.17it/s]

Noticias:   4%|▎         | 13/360 [00:09<04:30,  1.28it/s]

Noticias:   4%|▍         | 14/360 [00:10<04:54,  1.17it/s]

Noticias:   4%|▍         | 15/360 [00:12<06:01,  1.05s/it]

Noticias:   4%|▍         | 16/360 [00:13<06:35,  1.15s/it]

Noticias:   5%|▍         | 17/360 [00:14<06:13,  1.09s/it]

Noticias:   5%|▌         | 18/360 [00:15<06:18,  1.11s/it]

Noticias:   5%|▌         | 19/360 [00:16<05:33,  1.02it/s]

Noticias:   6%|▌         | 20/360 [00:18<06:25,  1.13s/it]

Noticias:   6%|▌         | 21/360 [00:19<07:13,  1.28s/it]

Noticias:   6%|▌         | 22/360 [00:21<07:19,  1.30s/it]

Noticias:   6%|▋         | 23/360 [00:22<06:53,  1.23s/it]

Noticias:   7%|▋         | 24/360 [00:22<06:08,  1.10s/it]

Noticias:   7%|▋         | 25/360 [00:23<06:00,  1.07s/it]

Noticias:   7%|▋         | 26/360 [00:25<06:38,  1.19s/it]

Noticias:   8%|▊         | 27/360 [00:26<06:27,  1.16s/it]

Noticias:   8%|▊         | 28/360 [00:27<06:11,  1.12s/it]

Noticias:   8%|▊         | 29/360 [00:28<06:22,  1.15s/it]

Noticias:   8%|▊         | 30/360 [00:29<06:07,  1.11s/it]

Noticias:   9%|▊         | 31/360 [00:30<05:57,  1.09s/it]

Noticias:   9%|▉         | 32/360 [00:32<06:11,  1.13s/it]

Noticias:   9%|▉         | 33/360 [00:33<05:59,  1.10s/it]

Noticias:   9%|▉         | 34/360 [00:33<05:23,  1.01it/s]

Noticias:  10%|▉         | 35/360 [00:34<05:15,  1.03it/s]

Noticias:  10%|█         | 36/360 [00:36<06:37,  1.23s/it]

Noticias:  10%|█         | 37/360 [00:37<06:14,  1.16s/it]

Noticias:  11%|█         | 38/360 [00:38<06:01,  1.12s/it]

Noticias:  11%|█         | 39/360 [00:39<05:54,  1.11s/it]

Noticias:  11%|█         | 40/360 [00:43<09:27,  1.77s/it]

Noticias:  11%|█▏        | 41/360 [00:44<09:14,  1.74s/it]

Noticias:  12%|█▏        | 42/360 [00:45<08:05,  1.53s/it]

Noticias:  12%|█▏        | 43/360 [00:46<07:23,  1.40s/it]

Noticias:  12%|█▏        | 44/360 [00:47<06:27,  1.23s/it]

Noticias:  12%|█▎        | 45/360 [00:48<05:48,  1.11s/it]

Noticias:  13%|█▎        | 46/360 [00:49<05:30,  1.05s/it]

Noticias:  13%|█▎        | 47/360 [00:51<06:24,  1.23s/it]

Noticias:  13%|█▎        | 48/360 [00:52<06:52,  1.32s/it]

Noticias:  14%|█▎        | 49/360 [00:53<06:23,  1.23s/it]

Noticias:  14%|█▍        | 50/360 [00:54<05:42,  1.11s/it]

Noticias:  14%|█▍        | 51/360 [00:56<06:31,  1.27s/it]

Noticias:  14%|█▍        | 52/360 [00:57<07:23,  1.44s/it]

Noticias:  15%|█▍        | 53/360 [00:59<07:58,  1.56s/it]

Noticias:  15%|█▌        | 54/360 [01:00<07:02,  1.38s/it]

Noticias:  15%|█▌        | 55/360 [01:02<08:02,  1.58s/it]

Noticias:  16%|█▌        | 56/360 [01:03<06:55,  1.37s/it]

Noticias:  16%|█▌        | 57/360 [01:04<06:03,  1.20s/it]

Noticias:  16%|█▌        | 58/360 [01:05<05:55,  1.18s/it]

Noticias:  16%|█▋        | 59/360 [01:06<05:49,  1.16s/it]

Noticias:  17%|█▋        | 60/360 [01:07<06:02,  1.21s/it]

Noticias:  17%|█▋        | 61/360 [01:10<08:10,  1.64s/it]

Noticias:  17%|█▋        | 62/360 [01:12<07:45,  1.56s/it]

Noticias:  18%|█▊        | 63/360 [01:13<07:49,  1.58s/it]

Noticias:  18%|█▊        | 64/360 [01:14<06:58,  1.42s/it]

Noticias:  18%|█▊        | 65/360 [01:15<05:54,  1.20s/it]

Noticias:  18%|█▊        | 66/360 [01:16<05:35,  1.14s/it]

Noticias:  19%|█▊        | 67/360 [01:17<05:06,  1.05s/it]

Noticias:  19%|█▉        | 68/360 [01:18<05:39,  1.16s/it]

Noticias:  19%|█▉        | 69/360 [01:20<06:09,  1.27s/it]

Noticias:  19%|█▉        | 70/360 [01:21<05:37,  1.16s/it]

Noticias:  20%|█▉        | 71/360 [01:22<05:21,  1.11s/it]

Noticias:  20%|██        | 72/360 [01:23<05:19,  1.11s/it]

Noticias:  20%|██        | 73/360 [01:24<05:35,  1.17s/it]

Noticias:  21%|██        | 74/360 [01:25<05:19,  1.12s/it]

Noticias:  21%|██        | 75/360 [01:26<05:01,  1.06s/it]

Noticias:  21%|██        | 76/360 [01:27<04:45,  1.01s/it]

Noticias:  21%|██▏       | 77/360 [01:28<05:39,  1.20s/it]

Noticias:  22%|██▏       | 78/360 [01:30<06:14,  1.33s/it]

Noticias:  22%|██▏       | 79/360 [01:32<06:29,  1.39s/it]

Noticias:  22%|██▏       | 80/360 [01:33<06:40,  1.43s/it]

Noticias:  22%|██▎       | 81/360 [01:34<06:14,  1.34s/it]

Noticias:  23%|██▎       | 82/360 [01:36<06:25,  1.39s/it]

Noticias:  23%|██▎       | 83/360 [01:37<06:21,  1.38s/it]

Noticias:  23%|██▎       | 84/360 [01:39<06:42,  1.46s/it]

Noticias:  24%|██▎       | 85/360 [01:40<06:57,  1.52s/it]

Noticias:  24%|██▍       | 86/360 [01:42<06:47,  1.49s/it]

Noticias:  24%|██▍       | 87/360 [01:43<06:43,  1.48s/it]

Noticias:  24%|██▍       | 88/360 [01:44<06:18,  1.39s/it]

Noticias:  25%|██▍       | 89/360 [01:46<06:38,  1.47s/it]

Noticias:  25%|██▌       | 90/360 [01:48<07:00,  1.56s/it]

Noticias:  25%|██▌       | 91/360 [01:49<06:55,  1.55s/it]

Noticias:  26%|██▌       | 92/360 [01:51<06:36,  1.48s/it]

Noticias:  26%|██▌       | 93/360 [01:52<05:48,  1.31s/it]

Noticias:  26%|██▌       | 94/360 [01:53<05:43,  1.29s/it]

Noticias:  26%|██▋       | 95/360 [01:55<06:12,  1.41s/it]

Noticias:  27%|██▋       | 96/360 [01:56<06:49,  1.55s/it]

Noticias:  27%|██▋       | 97/360 [01:58<06:31,  1.49s/it]

Noticias:  27%|██▋       | 98/360 [01:59<05:53,  1.35s/it]

Noticias:  28%|██▊       | 99/360 [02:01<07:02,  1.62s/it]

Noticias:  28%|██▊       | 100/360 [02:02<06:01,  1.39s/it]

Noticias:  28%|██▊       | 101/360 [02:03<05:29,  1.27s/it]

Noticias:  28%|██▊       | 102/360 [02:04<05:00,  1.16s/it]

Noticias:  29%|██▊       | 103/360 [02:07<07:19,  1.71s/it]

Noticias:  29%|██▉       | 104/360 [02:09<07:19,  1.72s/it]

Noticias:  29%|██▉       | 105/360 [02:09<05:55,  1.39s/it]

Noticias:  29%|██▉       | 106/360 [02:10<04:59,  1.18s/it]

Noticias:  30%|██▉       | 107/360 [02:10<04:12,  1.00it/s]

Noticias:  30%|███       | 108/360 [02:11<04:14,  1.01s/it]

Noticias:  30%|███       | 109/360 [02:16<08:19,  1.99s/it]

Noticias:  31%|███       | 110/360 [02:17<07:10,  1.72s/it]

Noticias:  31%|███       | 111/360 [02:18<06:16,  1.51s/it]

Noticias:  31%|███       | 112/360 [02:19<05:24,  1.31s/it]

Noticias:  31%|███▏      | 113/360 [02:20<04:48,  1.17s/it]

Noticias:  32%|███▏      | 114/360 [02:21<04:33,  1.11s/it]

Noticias:  32%|███▏      | 115/360 [02:22<04:57,  1.21s/it]

Noticias:  32%|███▏      | 116/360 [02:23<05:04,  1.25s/it]

Noticias:  32%|███▎      | 117/360 [02:24<04:31,  1.12s/it]

Noticias:  33%|███▎      | 118/360 [02:25<04:14,  1.05s/it]

Noticias:  33%|███▎      | 119/360 [02:26<04:10,  1.04s/it]

Noticias:  33%|███▎      | 120/360 [02:27<04:33,  1.14s/it]

Noticias:  34%|███▎      | 121/360 [02:28<04:06,  1.03s/it]

Noticias:  34%|███▍      | 122/360 [02:30<05:28,  1.38s/it]

Noticias:  34%|███▍      | 123/360 [02:31<05:08,  1.30s/it]

Noticias:  34%|███▍      | 124/360 [02:33<05:47,  1.47s/it]

Noticias:  35%|███▍      | 125/360 [02:35<05:33,  1.42s/it]

Noticias:  35%|███▌      | 126/360 [02:36<05:33,  1.42s/it]

Noticias:  35%|███▌      | 127/360 [02:37<05:24,  1.39s/it]

Noticias:  36%|███▌      | 128/360 [02:39<05:05,  1.32s/it]

Noticias:  36%|███▌      | 129/360 [02:40<05:20,  1.39s/it]

Noticias:  36%|███▌      | 130/360 [02:41<05:08,  1.34s/it]

Noticias:  36%|███▋      | 131/360 [02:44<06:05,  1.60s/it]

Noticias:  37%|███▋      | 132/360 [02:45<05:47,  1.53s/it]

Noticias:  37%|███▋      | 133/360 [02:46<05:26,  1.44s/it]

Noticias:  37%|███▋      | 134/360 [02:48<05:33,  1.48s/it]

Noticias:  38%|███▊      | 135/360 [02:49<05:27,  1.46s/it]

Noticias:  38%|███▊      | 136/360 [02:51<05:39,  1.52s/it]

Noticias:  38%|███▊      | 137/360 [02:52<05:52,  1.58s/it]

Noticias:  38%|███▊      | 138/360 [02:54<05:40,  1.53s/it]

Noticias:  39%|███▊      | 139/360 [02:55<05:39,  1.54s/it]

Noticias:  39%|███▉      | 140/360 [02:57<05:37,  1.53s/it]

Noticias:  39%|███▉      | 141/360 [03:00<07:16,  1.99s/it]

Noticias:  39%|███▉      | 142/360 [03:02<06:52,  1.89s/it]

Noticias:  40%|███▉      | 143/360 [03:03<06:26,  1.78s/it]

Noticias:  40%|████      | 144/360 [03:05<06:02,  1.68s/it]

Noticias:  40%|████      | 145/360 [03:08<08:19,  2.32s/it]

Noticias:  41%|████      | 146/360 [03:10<07:31,  2.11s/it]

Noticias:  41%|████      | 147/360 [03:12<06:59,  1.97s/it]

Noticias:  41%|████      | 148/360 [03:15<08:02,  2.28s/it]

Noticias:  41%|████▏     | 149/360 [03:16<07:04,  2.01s/it]

Noticias:  42%|████▏     | 150/360 [03:18<06:54,  1.97s/it]

Noticias:  42%|████▏     | 151/360 [03:20<06:23,  1.84s/it]

Noticias:  42%|████▏     | 152/360 [03:21<06:21,  1.83s/it]

Noticias:  42%|████▎     | 153/360 [03:23<06:00,  1.74s/it]

Noticias:  43%|████▎     | 154/360 [03:24<05:46,  1.68s/it]

Noticias:  43%|████▎     | 155/360 [03:26<05:32,  1.62s/it]

Noticias:  43%|████▎     | 156/360 [03:27<05:22,  1.58s/it]

Noticias:  44%|████▎     | 157/360 [03:29<05:48,  1.72s/it]

Noticias:  44%|████▍     | 158/360 [03:31<05:51,  1.74s/it]

Noticias:  44%|████▍     | 159/360 [03:32<05:22,  1.60s/it]

Noticias:  44%|████▍     | 160/360 [03:34<05:41,  1.71s/it]

Noticias:  45%|████▍     | 161/360 [03:36<05:17,  1.60s/it]

Noticias:  45%|████▌     | 162/360 [03:39<07:08,  2.16s/it]

Noticias:  45%|████▌     | 163/360 [03:40<05:57,  1.82s/it]

Noticias:  46%|████▌     | 164/360 [03:42<05:40,  1.74s/it]

Noticias:  46%|████▌     | 165/360 [03:43<05:12,  1.60s/it]

Noticias:  46%|████▌     | 166/360 [03:44<04:49,  1.49s/it]

Noticias:  46%|████▋     | 167/360 [03:46<04:45,  1.48s/it]

Noticias:  47%|████▋     | 168/360 [03:47<04:07,  1.29s/it]

Noticias:  47%|████▋     | 169/360 [03:48<03:50,  1.21s/it]

Noticias:  47%|████▋     | 170/360 [03:49<04:07,  1.30s/it]

Noticias:  48%|████▊     | 171/360 [03:51<04:24,  1.40s/it]

Noticias:  48%|████▊     | 172/360 [03:52<04:13,  1.35s/it]

Noticias:  48%|████▊     | 173/360 [03:53<04:17,  1.38s/it]

Noticias:  48%|████▊     | 174/360 [03:55<04:35,  1.48s/it]

Noticias:  49%|████▊     | 175/360 [03:57<04:39,  1.51s/it]

Noticias:  49%|████▉     | 176/360 [03:58<04:43,  1.54s/it]

Noticias:  49%|████▉     | 177/360 [04:00<04:41,  1.54s/it]

Noticias:  49%|████▉     | 178/360 [04:01<04:03,  1.34s/it]

Noticias:  50%|████▉     | 179/360 [04:02<04:11,  1.39s/it]

Noticias:  50%|█████     | 180/360 [04:04<04:10,  1.39s/it]

Noticias:  50%|█████     | 181/360 [04:05<03:39,  1.22s/it]

Noticias:  51%|█████     | 182/360 [04:05<03:11,  1.07s/it]

Noticias:  51%|█████     | 183/360 [04:06<02:44,  1.07it/s]

Noticias:  51%|█████     | 184/360 [04:07<02:50,  1.03it/s]

Noticias:  51%|█████▏    | 185/360 [04:09<03:24,  1.17s/it]

Noticias:  52%|█████▏    | 186/360 [04:10<03:36,  1.24s/it]

Noticias:  52%|█████▏    | 187/360 [04:11<03:19,  1.15s/it]

Noticias:  52%|█████▏    | 188/360 [04:12<03:10,  1.10s/it]

Noticias:  52%|█████▎    | 189/360 [04:13<03:05,  1.08s/it]

Noticias:  53%|█████▎    | 190/360 [04:14<03:19,  1.17s/it]

Noticias:  53%|█████▎    | 191/360 [04:16<03:34,  1.27s/it]

Noticias:  53%|█████▎    | 192/360 [04:16<02:59,  1.07s/it]

Noticias:  54%|█████▎    | 193/360 [04:17<02:51,  1.03s/it]

Noticias:  54%|█████▍    | 194/360 [04:18<02:32,  1.09it/s]

Noticias:  54%|█████▍    | 195/360 [04:19<02:15,  1.22it/s]

Noticias:  54%|█████▍    | 196/360 [04:19<02:13,  1.23it/s]

Noticias:  55%|█████▍    | 197/360 [04:22<03:47,  1.40s/it]

Noticias:  55%|█████▌    | 198/360 [04:24<03:48,  1.41s/it]

Noticias:  55%|█████▌    | 199/360 [04:25<03:56,  1.47s/it]

Noticias:  56%|█████▌    | 200/360 [04:27<03:55,  1.47s/it]

Noticias:  56%|█████▌    | 201/360 [04:29<04:17,  1.62s/it]

Noticias:  56%|█████▌    | 202/360 [04:30<04:10,  1.59s/it]

Noticias:  56%|█████▋    | 203/360 [04:32<04:11,  1.60s/it]

Noticias:  57%|█████▋    | 204/360 [04:32<03:22,  1.30s/it]

Noticias:  57%|█████▋    | 205/360 [04:34<03:30,  1.36s/it]

Noticias:  57%|█████▋    | 206/360 [04:35<03:31,  1.37s/it]

Noticias:  57%|█████▊    | 207/360 [04:37<03:27,  1.36s/it]

Noticias:  58%|█████▊    | 208/360 [04:38<03:26,  1.36s/it]

Noticias:  58%|█████▊    | 209/360 [04:42<05:14,  2.08s/it]

Noticias:  58%|█████▊    | 210/360 [04:43<04:42,  1.89s/it]

Noticias:  59%|█████▊    | 211/360 [04:45<04:57,  2.00s/it]

Noticias:  59%|█████▉    | 212/360 [04:46<04:07,  1.67s/it]

Noticias:  59%|█████▉    | 213/360 [04:48<03:47,  1.55s/it]

Noticias:  59%|█████▉    | 214/360 [04:49<03:35,  1.47s/it]

Noticias:  60%|█████▉    | 215/360 [04:50<03:27,  1.43s/it]

Noticias:  60%|██████    | 216/360 [04:52<03:30,  1.46s/it]

Noticias:  60%|██████    | 217/360 [04:53<03:24,  1.43s/it]

Noticias:  61%|██████    | 218/360 [04:54<03:18,  1.40s/it]

Noticias:  61%|██████    | 219/360 [04:55<02:52,  1.22s/it]

Noticias:  61%|██████    | 220/360 [04:57<03:13,  1.38s/it]

Noticias:  61%|██████▏   | 221/360 [04:59<03:23,  1.46s/it]

Noticias:  62%|██████▏   | 222/360 [05:00<03:18,  1.44s/it]

Noticias:  62%|██████▏   | 223/360 [05:02<03:26,  1.51s/it]

Noticias:  62%|██████▏   | 224/360 [05:03<03:13,  1.42s/it]

Noticias:  62%|██████▎   | 225/360 [05:04<03:12,  1.43s/it]

Noticias:  63%|██████▎   | 226/360 [05:05<02:55,  1.31s/it]

Noticias:  63%|██████▎   | 227/360 [05:07<03:02,  1.37s/it]

Noticias:  63%|██████▎   | 228/360 [05:09<03:10,  1.45s/it]

Noticias:  64%|██████▎   | 229/360 [05:10<03:03,  1.40s/it]

Noticias:  64%|██████▍   | 230/360 [05:11<02:58,  1.37s/it]

Noticias:  64%|██████▍   | 231/360 [05:12<02:43,  1.27s/it]

Noticias:  64%|██████▍   | 232/360 [05:14<02:47,  1.31s/it]

Noticias:  65%|██████▍   | 233/360 [05:14<02:32,  1.20s/it]

Noticias:  65%|██████▌   | 234/360 [05:15<02:10,  1.04s/it]

Noticias:  65%|██████▌   | 235/360 [05:17<02:34,  1.24s/it]

Noticias:  66%|██████▌   | 236/360 [05:19<02:57,  1.43s/it]

Noticias:  66%|██████▌   | 237/360 [05:20<02:58,  1.45s/it]

Noticias:  66%|██████▌   | 238/360 [05:22<03:03,  1.50s/it]

Noticias:  66%|██████▋   | 239/360 [05:23<03:03,  1.52s/it]

Noticias:  67%|██████▋   | 240/360 [05:25<03:09,  1.58s/it]

Noticias:  67%|██████▋   | 241/360 [05:26<02:55,  1.48s/it]

Noticias:  67%|██████▋   | 242/360 [05:28<02:56,  1.49s/it]

Noticias:  68%|██████▊   | 243/360 [05:29<02:49,  1.45s/it]

Noticias:  68%|██████▊   | 244/360 [05:31<02:50,  1.47s/it]

Noticias:  68%|██████▊   | 245/360 [05:32<02:48,  1.47s/it]

Noticias:  68%|██████▊   | 246/360 [05:34<02:56,  1.54s/it]

Noticias:  69%|██████▊   | 247/360 [05:35<02:50,  1.51s/it]

Noticias:  69%|██████▉   | 248/360 [05:37<02:46,  1.49s/it]

Noticias:  69%|██████▉   | 249/360 [05:39<02:56,  1.59s/it]

Noticias:  69%|██████▉   | 250/360 [05:40<02:57,  1.61s/it]

Noticias:  70%|██████▉   | 251/360 [05:42<02:44,  1.51s/it]

Noticias:  70%|███████   | 252/360 [05:43<02:45,  1.53s/it]

Noticias:  70%|███████   | 253/360 [05:44<02:34,  1.45s/it]

Noticias:  71%|███████   | 254/360 [05:46<02:34,  1.46s/it]

Noticias:  71%|███████   | 255/360 [05:47<02:36,  1.49s/it]

Noticias:  71%|███████   | 256/360 [05:49<02:36,  1.50s/it]

Noticias:  71%|███████▏  | 257/360 [05:51<02:42,  1.57s/it]

Noticias:  72%|███████▏  | 258/360 [05:52<02:30,  1.47s/it]

Noticias:  72%|███████▏  | 259/360 [05:54<02:32,  1.51s/it]

Noticias:  72%|███████▏  | 260/360 [05:55<02:42,  1.62s/it]

Noticias:  72%|███████▎  | 261/360 [05:57<02:47,  1.69s/it]

Noticias:  73%|███████▎  | 262/360 [05:59<02:43,  1.67s/it]

Noticias:  73%|███████▎  | 263/360 [06:00<02:20,  1.45s/it]

Noticias:  73%|███████▎  | 264/360 [06:01<02:00,  1.25s/it]

Noticias:  74%|███████▎  | 265/360 [06:02<02:08,  1.35s/it]

Noticias:  74%|███████▍  | 266/360 [06:04<02:14,  1.43s/it]

Noticias:  74%|███████▍  | 267/360 [06:05<02:12,  1.43s/it]

Noticias:  74%|███████▍  | 268/360 [06:06<01:51,  1.21s/it]

Noticias:  75%|███████▍  | 269/360 [06:07<01:48,  1.19s/it]

Noticias:  75%|███████▌  | 270/360 [06:09<02:04,  1.38s/it]

Noticias:  75%|███████▌  | 271/360 [06:10<01:51,  1.25s/it]

Noticias:  76%|███████▌  | 272/360 [06:12<02:16,  1.56s/it]

Noticias:  76%|███████▌  | 273/360 [06:13<02:08,  1.48s/it]

Noticias:  76%|███████▌  | 274/360 [06:14<01:50,  1.28s/it]

Noticias:  76%|███████▋  | 275/360 [06:16<01:50,  1.30s/it]

Noticias:  77%|███████▋  | 276/360 [06:16<01:36,  1.15s/it]

Noticias:  77%|███████▋  | 277/360 [06:18<01:45,  1.27s/it]

Noticias:  77%|███████▋  | 278/360 [06:19<01:35,  1.16s/it]

Noticias:  78%|███████▊  | 279/360 [06:21<01:45,  1.31s/it]

Noticias:  78%|███████▊  | 280/360 [06:22<01:53,  1.41s/it]

Noticias:  78%|███████▊  | 281/360 [06:24<01:49,  1.38s/it]

Noticias:  78%|███████▊  | 282/360 [06:25<01:51,  1.43s/it]

Noticias:  79%|███████▊  | 283/360 [06:27<01:52,  1.46s/it]

Noticias:  79%|███████▉  | 284/360 [06:28<01:51,  1.46s/it]

Noticias:  79%|███████▉  | 285/360 [06:30<01:57,  1.57s/it]

Noticias:  79%|███████▉  | 286/360 [06:32<01:57,  1.59s/it]

Noticias:  80%|███████▉  | 287/360 [06:34<02:15,  1.85s/it]

Noticias:  80%|████████  | 288/360 [06:35<02:04,  1.73s/it]

Noticias:  80%|████████  | 289/360 [06:37<02:01,  1.71s/it]

Noticias:  81%|████████  | 290/360 [06:39<02:08,  1.83s/it]

Noticias:  81%|████████  | 291/360 [06:41<02:00,  1.74s/it]

Noticias:  81%|████████  | 292/360 [06:42<01:54,  1.68s/it]

Noticias:  81%|████████▏ | 293/360 [06:44<01:51,  1.67s/it]

Noticias:  82%|████████▏ | 294/360 [06:45<01:34,  1.43s/it]

Noticias:  82%|████████▏ | 295/360 [06:46<01:35,  1.47s/it]

Noticias:  82%|████████▏ | 296/360 [06:48<01:33,  1.46s/it]

Noticias:  82%|████████▎ | 297/360 [06:50<01:43,  1.64s/it]

Noticias:  83%|████████▎ | 298/360 [06:51<01:36,  1.55s/it]

Noticias:  83%|████████▎ | 299/360 [06:53<01:34,  1.54s/it]

Noticias:  83%|████████▎ | 300/360 [06:54<01:28,  1.48s/it]

Noticias:  84%|████████▎ | 301/360 [06:55<01:26,  1.46s/it]

Noticias:  84%|████████▍ | 302/360 [06:57<01:24,  1.46s/it]

Noticias:  84%|████████▍ | 303/360 [06:58<01:24,  1.48s/it]

Noticias:  84%|████████▍ | 304/360 [07:00<01:27,  1.56s/it]

Noticias:  85%|████████▍ | 305/360 [07:02<01:23,  1.52s/it]

Noticias:  85%|████████▌ | 306/360 [07:03<01:27,  1.61s/it]

Noticias:  85%|████████▌ | 307/360 [07:05<01:20,  1.52s/it]

Noticias:  86%|████████▌ | 308/360 [07:06<01:16,  1.48s/it]

Noticias:  86%|████████▌ | 309/360 [07:08<01:16,  1.49s/it]

Noticias:  86%|████████▌ | 310/360 [07:10<01:24,  1.69s/it]

Noticias:  86%|████████▋ | 311/360 [07:12<01:23,  1.71s/it]

Noticias:  87%|████████▋ | 312/360 [07:13<01:15,  1.58s/it]

Noticias:  87%|████████▋ | 313/360 [07:14<01:12,  1.55s/it]

Noticias:  87%|████████▋ | 314/360 [07:16<01:12,  1.58s/it]

Noticias:  88%|████████▊ | 315/360 [07:17<01:06,  1.47s/it]

Noticias:  88%|████████▊ | 316/360 [07:18<01:01,  1.40s/it]

Noticias:  88%|████████▊ | 317/360 [07:20<01:00,  1.42s/it]

Noticias:  88%|████████▊ | 318/360 [07:21<00:59,  1.41s/it]

Noticias:  89%|████████▊ | 319/360 [07:23<00:59,  1.46s/it]

Noticias:  89%|████████▉ | 320/360 [07:25<01:01,  1.54s/it]

Noticias:  89%|████████▉ | 321/360 [07:26<01:02,  1.59s/it]

Noticias:  89%|████████▉ | 322/360 [07:28<00:59,  1.58s/it]

Noticias:  90%|████████▉ | 323/360 [07:29<00:55,  1.50s/it]

Noticias:  90%|█████████ | 324/360 [07:30<00:51,  1.43s/it]

Noticias:  90%|█████████ | 325/360 [07:32<00:49,  1.43s/it]

Noticias:  91%|█████████ | 326/360 [07:34<00:56,  1.67s/it]

Noticias:  91%|█████████ | 327/360 [07:35<00:52,  1.60s/it]

Noticias:  91%|█████████ | 328/360 [07:37<00:48,  1.52s/it]

Noticias:  91%|█████████▏| 329/360 [07:38<00:46,  1.50s/it]

Noticias:  92%|█████████▏| 330/360 [07:40<00:44,  1.49s/it]

Noticias:  92%|█████████▏| 331/360 [07:42<00:45,  1.57s/it]

Noticias:  92%|█████████▏| 332/360 [07:43<00:43,  1.57s/it]

Noticias:  92%|█████████▎| 333/360 [07:45<00:41,  1.55s/it]

Noticias:  93%|█████████▎| 334/360 [07:46<00:38,  1.49s/it]

Noticias:  93%|█████████▎| 335/360 [07:49<00:52,  2.09s/it]

Noticias:  93%|█████████▎| 336/360 [07:51<00:47,  1.99s/it]

Noticias:  94%|█████████▎| 337/360 [07:53<00:41,  1.82s/it]

Noticias:  94%|█████████▍| 338/360 [07:54<00:36,  1.67s/it]

Noticias:  94%|█████████▍| 339/360 [07:56<00:38,  1.82s/it]

Noticias:  94%|█████████▍| 340/360 [07:58<00:34,  1.70s/it]

Noticias:  95%|█████████▍| 341/360 [07:59<00:33,  1.74s/it]

Noticias:  95%|█████████▌| 342/360 [08:01<00:30,  1.68s/it]

Noticias:  95%|█████████▌| 343/360 [08:03<00:32,  1.92s/it]

Noticias:  96%|█████████▌| 344/360 [08:05<00:28,  1.77s/it]

Noticias:  96%|█████████▌| 345/360 [08:06<00:25,  1.70s/it]

Noticias:  96%|█████████▌| 346/360 [08:09<00:27,  1.96s/it]

Noticias:  96%|█████████▋| 347/360 [08:10<00:22,  1.73s/it]

Noticias:  97%|█████████▋| 348/360 [08:12<00:19,  1.66s/it]

Noticias:  97%|█████████▋| 349/360 [08:16<00:28,  2.58s/it]

Noticias:  97%|█████████▋| 350/360 [08:18<00:22,  2.22s/it]

Noticias:  98%|█████████▊| 351/360 [08:19<00:18,  2.01s/it]

Noticias:  98%|█████████▊| 352/360 [08:21<00:14,  1.81s/it]

Noticias:  98%|█████████▊| 353/360 [08:22<00:11,  1.67s/it]

Noticias:  98%|█████████▊| 354/360 [08:23<00:08,  1.44s/it]

Noticias:  99%|█████████▊| 355/360 [08:24<00:07,  1.46s/it]

Noticias:  99%|█████████▉| 356/360 [08:26<00:05,  1.49s/it]

Noticias:  99%|█████████▉| 357/360 [08:27<00:04,  1.48s/it]

Noticias:  99%|█████████▉| 358/360 [08:29<00:02,  1.44s/it]

Noticias: 100%|█████████▉| 359/360 [08:30<00:01,  1.40s/it]

Noticias: 100%|██████████| 360/360 [08:31<00:00,  1.34s/it]

Noticias: 100%|██████████| 360/360 [08:31<00:00,  1.42s/it]

(360, 7)

## 2. Limpieza

In [5]:
df["medio"] = MEDIO
df["fecha"] = df["publicado"].str[:10]  # AAAA-MM-DD (hora de Lima)
df["etiqueta"] = df["seccion_web"].map(SECCIONES)
for col in ["titular", "bajada"]:
    df[col] = df[col].str.replace(r"\s+", " ", regex=True).str.strip()

df = df[["titular", "bajada", "medio", "seccion_original", "url", "fecha", "etiqueta"]]

assert len(df) >= 350 and df["url"].is_unique
print(df.isna().sum())
df["etiqueta"].value_counts()

titular             0
bajada              0
medio               0
seccion_original    0
url                 0
fecha               0
etiqueta            0
dtype: int64

etiqueta
deportes              90
economia              90
politica              90
ciencia_tecnologia    90
Name: count, dtype: int64

## 3. Exportación

Se guarda `datos/noticias.csv` con las 7 columnas y se vuelve a leer el archivo para comprobar lo que quedó guardado. Va antes del EDA porque el análisis se hace sobre este archivo.

In [6]:
ruta = DATOS / "noticias.csv"
df.to_csv(ruta, index=False)

df = pd.read_csv(ruta)  # se lee de nuevo para verificar el archivo exportado
assert df.shape[1] == 7

print("df.shape:", df.shape)
df.head()

df.shape: (360, 7)

,titular,bajada,medio,seccion_original,url,fecha,etiqueta
0,"Balón de Oro 2026 EN VIVO, ceremonia en directo",Balón de Oro 2026 EN VIVO: ver transmisión del...,El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes
1,¿A qué hora se da el Balón de Oro 2026 y quién...,"Horarios del inicio del Balón de Oro 2026 hoy,...",El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes
2,¿En qué canal EN VIVO transmiten Ceremonia del...,Revisa qué canales TV transmiten la ceremonia ...,El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes
3,DAZN EN VIVO GRATIS - Entrega del Balón de Oro...,DAZN EN VIVO GRATIS: ver transmisión de la Cer...,El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes
4,¿Quién ganó el Balón de Oro 2026? Resultados o...,Conoce quién fue el ganador de Balón de Oro 20...,El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes

## 4. Análisis exploratorio (EDA)

Tres gráficos con Plotly Express. El título de cada uno expresa la conclusión y se calcula a partir de los datos, así que sigue siendo correcto si se vuelven a descargar las noticias.

Esta celda lee `datos/noticias.csv`, por lo que basta con haber ejecutado la sección 0.

In [7]:
noticias = pd.read_csv(DATOS / "noticias.csv", parse_dates=["fecha"])

NOMBRES = {
    "economia": "Economía",
    "politica": "Política",
    "deportes": "Deportes",
    "ciencia_tecnologia": "Ciencia y Tecnología",
}
ORDEN = list(NOMBRES.values())
COLORES = dict(zip(ORDEN, ["#2a78d6", "#eb6834", "#1baf7a", "#eda100"]))  # mismo color por categoría en todos los gráficos
ESTILO = dict(template="plotly_white", barcornerradius=4, title_x=0.01)

noticias["categoria"] = noticias["etiqueta"].map(NOMBRES)
noticias.head()

,titular,bajada,medio,seccion_original,url,fecha,etiqueta,categoria
0,"Balón de Oro 2026 EN VIVO, ceremonia en directo",Balón de Oro 2026 EN VIVO: ver transmisión del...,El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes,Deportes
1,¿A qué hora se da el Balón de Oro 2026 y quién...,"Horarios del inicio del Balón de Oro 2026 hoy,...",El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes,Deportes
2,¿En qué canal EN VIVO transmiten Ceremonia del...,Revisa qué canales TV transmiten la ceremonia ...,El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes,Deportes
3,DAZN EN VIVO GRATIS - Entrega del Balón de Oro...,DAZN EN VIVO GRATIS: ver transmisión de la Cer...,El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes,Deportes
4,¿Quién ganó el Balón de Oro 2026? Resultados o...,Conoce quién fue el ganador de Balón de Oro 20...,El Comercio,deporte-total-futbol-mundial,https://elcomercio.pe/deporte-total/futbol-mun...,2026-10-26,deportes,Deportes

### 4.1 Distribución de noticias por categoría

In [8]:
por_categoria = (
    noticias["categoria"].value_counts().reindex(ORDEN)
    .rename_axis("categoria").reset_index(name="noticias")
)
por_categoria["porcentaje"] = por_categoria["noticias"] / por_categoria["noticias"].sum()

if por_categoria["noticias"].nunique() == 1:
    titulo = (f"Dataset balanceado: las {len(por_categoria)} categorías tienen "
              f"{por_categoria['noticias'].iloc[0]} noticias cada una")
else:
    mayor = por_categoria.loc[por_categoria["noticias"].idxmax()]
    titulo = f"{mayor.categoria} concentra el {mayor.porcentaje:.0%} de las noticias"

fig = px.bar(
    por_categoria, x="noticias", y="categoria", color="categoria", orientation="h", text="noticias",
    color_discrete_map=COLORES, hover_data={"porcentaje": ":.0%", "categoria": False},
    labels={"noticias": "Número de noticias", "categoria": "", "porcentaje": "Porcentaje"},
    title=titulo,
)
fig.update_layout(**ESTILO, showlegend=False, title_subtitle_text="Noticias por categoría (etiqueta)")
fig.update_yaxes(categoryorder="array", categoryarray=ORDEN[::-1])
fig.show()

### 4.2 Distribución de noticias por rango de fechas

Todas las noticias son de un solo medio (El Comercio), así que se analiza la distribución por fecha de publicación.

In [9]:
por_dia = noticias.groupby(["fecha", "categoria"]).size().reset_index(name="noticias")
dias = noticias.groupby("categoria")["fecha"].agg(lambda f: (f.max() - f.min()).days + 1)
rapida, lenta = dias.idxmin(), dias.idxmax()

titulo = (f"Las noticias de {rapida} caben en {dias[rapida]} días; "
          f"las de {lenta} abarcan {dias[lenta]}")
periodo = f"{noticias['fecha'].min():%d/%m} al {noticias['fecha'].max():%d/%m/%Y}"

fig = px.bar(
    por_dia, x="fecha", y="noticias", color="categoria",
    category_orders={"categoria": ORDEN}, color_discrete_map=COLORES,
    labels={"fecha": "Fecha de publicación", "noticias": "Número de noticias", "categoria": ""},
    title=titulo,
)
fig.update_layout(
    **ESTILO, bargap=0.15,
    title_subtitle_text=f"Noticias publicadas por día y categoría, del {periodo}",
)
fig.update_traces(marker_line_color="white", marker_line_width=1.5)
fig.update_xaxes(dtick="D1", tickformat="%d/%m")
fig.show()

dias.rename("días cubiertos").to_frame()

                      días cubiertos
categoria
Ciencia y Tecnología              15
Deportes                           3
Economía                           7
Política                           7

### 4.3 Longitud de los titulares

In [10]:
noticias["largo_titular"] = noticias["titular"].str.len()
q1, mediana, q3 = noticias["largo_titular"].quantile([0.25, 0.5, 0.75]).round().astype(int)

fig = px.histogram(
    noticias, x="largo_titular", nbins=25, color_discrete_sequence=[COLORES["Economía"]],
    labels={"largo_titular": "Longitud del titular (caracteres)"},
    title=f"La mitad de los titulares mide entre {q1} y {q3} caracteres (mediana: {mediana})",
)
fig.add_vline(x=mediana, line_dash="dash", line_color="#52514e",
              annotation_text=f"Mediana: {mediana}", annotation_position="top right")
fig.update_layout(
    **ESTILO, bargap=0.05, yaxis_title="Número de noticias",
    title_subtitle_text="Distribución de la longitud de los titulares",
)
fig.show()

noticias["largo_titular"].describe().round(1)

count    360.0
mean      95.7
std       25.2
min       13.0
25%       82.8
50%       97.0
75%      108.0
max      167.0
Name: largo_titular, dtype: float64

### 4.4 Validación: titulares más largos y más cortos

Se muestran los 5 titulares más largos y los 5 más cortos y se verifica que coincidan con el histograma: deben ser los extremos del eje X y, si son atípicos, quedar fuera del rango `Q1 − 1.5·IQR` a `Q3 + 1.5·IQR`.

In [11]:
COLUMNAS = ["largo_titular", "titular", "categoria", "seccion_original"]
mas_largos = noticias.nlargest(5, "largo_titular")[COLUMNAS]
mas_cortos = noticias.nsmallest(5, "largo_titular")[COLUMNAS]

with pd.option_context("display.max_colwidth", None):
    print("5 titulares más largos")
    display(mas_largos)
    print("5 titulares más cortos")
    display(mas_cortos)

5 titulares más largos

,largo_titular,titular,categoria,seccion_original
88,167,"“Tiene habilidad, falta musculatura” y “Aún es parte del universo de convocables”: cinco voces autorizadas sobre el futuro de Maxloren Castro en Cristal y la selección",Deportes,deporte-total-futbol-peruano
11,165,"“Para una hipotética final Alianza pediría árbitro y VAR extranjeros, además de goal line”: Alfredo Arosemena y su postura sobre el arbitraje, Paolo, Guede y Velazco",Deportes,deporte-total-futbol-peruano
26,160,El “Quedan 4 finales” de Guede y el cántico de 5 mil hinchas que coparon Moquegua: lo que no se vio del dramático 1-0 que mantiene vivo a Alianza en el Clausura,Deportes,deporte-total-futbol-peruano
74,158,“El culpable soy yo” de Mosquera y por qué sacó a Yotún con el 2-0 en contra: lo que no se vio del tropezón de Cristal en Cusco que lo deja en la cuerda floja,Deportes,deporte-total-futbol-peruano
241,157,Tomás Gálvez pide derogar ley que permite a la PNP investigación preliminar sin fiscales: “Ha generado un conflicto entre el Ministerio Público y la Policía”,Política,politica-justicia

5 titulares más cortos

     largo_titular                      titular categoria     seccion_original
208             13                Sillas vacías  Política  opinion-columnistas
258             15              El rol de Obras  Política     politica-opinion
206             17            El dictador feliz  Política  opinion-columnistas
97              25    El Niño no es la pandemia  Economía       economia-dia-1
172             27  Las muchas caras de El Niño  Economía     economia-opinion

In [12]:
iqr = q3 - q1
limite_inf, limite_sup = q1 - 1.5 * iqr, q3 + 1.5 * iqr
minimo, maximo = noticias["largo_titular"].min(), noticias["largo_titular"].max()

# Los extremos de las tablas deben ser los extremos del eje X del histograma
assert mas_cortos["largo_titular"].iloc[0] == minimo and mas_largos["largo_titular"].iloc[0] == maximo

print(f"Histograma: de {minimo} a {maximo} caracteres; mitad central entre {q1} y {q3} (mediana {mediana})")
print(f"Rango sin atípicos: {limite_inf:.0f} a {limite_sup:.0f} caracteres\n")
for nombre, grupo, limite, fuera in [
    ("Más cortos", mas_cortos, limite_inf, mas_cortos["largo_titular"] < limite_inf),
    ("Más largos", mas_largos, limite_sup, mas_largos["largo_titular"] > limite_sup),
]:
    # columna de opinión: lo indica la sección o la URL
    opinion = noticias.loc[grupo.index, ["seccion_original", "url"]].apply(lambda s: s.str.contains("opinion")).any(axis=1).sum()
    print(f"{nombre}: {grupo['largo_titular'].tolist()} caracteres -> "
          f"{fuera.sum()} de 5 son atípicos (límite {limite:.0f}); {opinion} de 5 son columnas de opinión")

Histograma: de 13 a 167 caracteres; mitad central entre 83 y 108 (mediana 97)
Rango sin atípicos: 46 a 146 caracteres

Más cortos: [13, 15, 17, 25, 27] caracteres -> 5 de 5 son atípicos (límite 46); 5 de 5 son columnas de opinión
Más largos: [167, 165, 160, 158, 157] caracteres -> 5 de 5 son atípicos (límite 146); 0 de 5 son columnas de opinión

**Conclusión de la validación** (descarga del 26/10/2026)

- Las tablas coinciden con el histograma: el titular más corto (13 caracteres) y el más largo (167) son los extremos del eje X, y los 10 están en las colas, fuera del rango sin atípicos (46 a 146).
- **Los más cortos son columnas de opinión** (*"Sillas vacías"*, *"El dictador feliz"*): usan títulos breves y metafóricos, a diferencia de las notas informativas. Explican la pequeña cola izquierda del histograma.
- **Los más largos son notas informativas, casi todas de Deportes** (fútbol peruano): combinan citas textuales con el contexto del partido, lo que alarga el titular.
- No hay titulares vacíos ni cortados: la longitud mínima corresponde a títulos reales.

## Conclusiones

Descarga del 26/10/2026, medio B (El Comercio).

1. **Extracción:** se obtuvieron **360 noticias** (mínimo exigido: 350) de 4 secciones, usando los sitemaps de noticias por sección para el listado y el HTML de cada nota para la bajada y la sección original. Hubo pausas entre todas las peticiones y quedó un respaldo crudo en `datos/raw/`.
2. **Calidad:** el dataset final tiene 7 columnas, sin valores vacíos ni URLs duplicadas, y se exportó a `datos/noticias.csv`.
3. **Balance:** las 4 categorías tienen 90 noticias cada una (25 %), así que no hace falta corregir desbalance de clases en el modelado.
4. **Ritmo de publicación:** con la misma cuota, Deportes cubre solo 3 días (unas 30 notas diarias), Economía y Política 7, y Ciencia y Tecnología 15. El periodo de cada categoría es distinto, lo que puede influir en los temas que aparecen (por ejemplo, el Balón de Oro en Deportes).
5. **Titulares:** la mitad mide entre 83 y 108 caracteres (mediana 97). La validación confirmó que los extremos del histograma son reales: los más cortos (13 a 27 caracteres) son columnas de opinión y los más largos (157 a 167) son notas de fútbol con citas textuales.
6. **Para la clasificación:** 15 de las 360 noticias son columnas de opinión publicadas en Política y Economía. Su estilo (títulos breves y metafóricos) puede hacerlas más difíciles de clasificar solo por el titular.